{{- if (include "fx-syncstorage.autogenerateSyncDb" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.syncserverdb.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.syncserverdb.auth.existingSecret }}
  labels:
    {{- include "fx-syncstorage.labels" . | nindent 4 }}
  {{- if .Values.syncstorage.keepGeneratedSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  mysql-root-password: {{- if $secret }}
    {{ index $secret.data "mysql-root-password" }}
  {{- else }}
    {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  mysql-password: {{- if $secret }}
    {{ index $secret.data "mysql-password" }}
  {{- else }}
    {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
{{- end }}
